import type { User } from './types/user';

export const defaultUsers: User[] = [
  {
    id: crypto.randomUUID(),
    firstName: 'Johan',
    lastName: 'Burden',
    gender: 'male',
    age: 21,
    hobbies: ['Archery', 'Diving'],
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Sophia',
    lastName: 'Martinez',
    gender: 'female',
    age: 28,
    hobbies: ['Hiking', 'Photography'],
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Liam',
    lastName: 'O’Connell',
    gender: 'male',
    age: 15,
    hobbies: ['Basketball', 'Gaming'],
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Ava',
    lastName: 'Patel',
    gender: 'female',
    age: 17,
    hobbies: ['Cooking', 'Gardening'],
  },
  {
    id: crypto.randomUUID(),
    firstName: 'David',
    lastName: 'Nguyen',
    gender: 'male',
    age: 27,
    hobbies: ['Cycling', 'Reading'],
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Emma',
    lastName: 'Dubois',
    gender: 'female',
    age: 30,
    hobbies: ['Yoga', 'Traveling'],
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Lucas',
    lastName: 'Gonzalez',
    gender: 'male',
    age: 16,
    hobbies: ['Rock Climbing', 'Swimming'],
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Olivia',
    lastName: 'Schmidt',
    gender: 'female',
    age: 26,
    hobbies: ['Painting', 'Volunteering'],
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Ethan',
    lastName: 'Kowalski',
    gender: 'male',
    age: 25,
    hobbies: ['Running', 'Fishing'],
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Isabella',
    lastName: 'Chen',
    gender: 'female',
    age: 17,
    hobbies: ['Dancing', 'Sculpting'],
  },
];
